%% define autoloads
OCTMESS = "octmess.oct";

for enum = {

%% functions from MESS_misc.cc
    "mess_init", "mess_version", "mess_eps", ...
    ...
%% functions from MESS_matrix.cc
    "mess_matrix", "mess_matrix_print", "mess_matrix_printdata", "mess_matrix_printinfo", "mess_matrix_printshort", ...
    ...
%% function from MESS_vector
    "mess_vector", "mess_vector_print", "mess_vector_printinfo", "mess_vector_printshort",...
    ...
%% functions from MESS_enum.cc
    "MESS_UNKNOWN", "MESS_CSR", "MESS_CSC", "MESS_DENSE", "MESS_COORD",...
    ...
    "MESS_EQN_NONE", "MESS_EQN_LYAP", "MESS_EQN_GLYAP", "MESS_EQN_RICCATI", "MESS_EQN_GRICCATI",...
    ...
    "MESS_MEMORY_LOW", "MESS_MEMORY_MID", "MESS_MEMORY_HIGH",...
    ...
    "MESS_OP_NONE", "MESS_OP_TRANSPOSE", "MESS_OP_HERMITIAN",...
    ...
    "MESS_LRCFADI_PARA_MINMAX", "MESS_LRCFADI_PARA_MINMAX_REAL", "MESS_LRCFADI_PARA_WACHSPRESS",...
    "MESS_LRCFADI_PARA_ADAPTIVE_V", "MESS_LRCFADI_PARA_ADAPTIVE",...
    ...
    "MESS_DIRECT_DEFAULT_LU", "MESS_DIRECT_SPARSE_LU", "MESS_DIRECT_LAPACK_LU", "MESS_DIRECT_UMFPACK_LU", "MESS_DIRECT_SUPERLU_LU", "MESS_DIRECT_CSPARSE_LU",...
    "MESS_DIRECT_BANDED_LU", "MESS_DIRECT_MKLPARDISO_LU",...
    ...
    "MESS_DIRECT_DEFAULT_CHOLESKY", "MESS_DIRECT_LAPACK_CHOLESKY", "MESS_DIRECT_CSPARSE_CHOLESKY", "MESS_DIRECT_CHOLMOD_CHOLESKY",...
    ...
    "MESS_MULTIDIRECT_SPARSE_LU", "MESS_MULTIDIRECT_UMFPACK_LU",...
    ...
    "MESS_RESIDUAL_INDEFINITE", "MESS_RESIDUAL_SPECTRAL",...
    ...
%% function from MESS_options
    "mess_options", "mess_options_print",...
    ...
%% function from MESS_status
    "mess_status", "mess_status_print",...
    ...
%% function from MESS_to_oct
    "mess_to_oct",

    }

    autoload(enum{:},OCTMESS);
end


%% call init to register all types
mess_init();


%% clear variables
clear OCTMESS;
