%MESS_LRADI  Algebraic Lyapunov Equation Solver
%
%   MESS_LRADI the Low-Rank ADI Lyapunov Equation solver.
%
%   MESS_LRADI solves various Lyapunov Equations generated by
%   the equation classes of MEX-M.E.S.S:
%
%   <a href="matlab:help mess_equation_glyap">mess_equation_glyap</a>
%   <a href="matlab:help mess_equation_glyap_dae1">mess_equation_glyap_dae1</a>
%   <a href="matlab:help mess_equation_glyap_dae2">mess_equation_glyap_dae2</a>
%   <a href="matlab:help mess_equation_glyap_so1">mess_equation_glyap_so1</a>
%   <a href="matlab:help mess_equation_glyap_so2">mess_equation_glyap_so2</a>
%
%   [Z,status] = MESS_LRADI(eqn,opt) solves the Lyapunov
%   Equation generated by an equation class of MEX-M.E.S.S.
%   opt is a <a href="matlab:help mess_options">mess_options</a> instances and contains the options of
%   the algorithm. The solution is returned as a Cholesky
%   factorization. status is a <a href="matlab:help mess_status">mess_status</a> instances and contains
%   informations about the ADI iteration.
%
%   Z = MESS_LRADI(eqn,opt) performs the same as [Z,status] = MESS_LRADI(eqn,opt)
%   but does not return a <a href="matlab:help mess_status">mess_status</a> instance.
%
%   Examples / Tests:
%       <a href="matlab:help example_lradi_rail">example_lradi_rail</a>, <a href="matlab:edit example_lradi_rail">example_lradi_rail.m</a>
%       <a href="matlab:help test_lradi_filter">test_lradi_filter</a>, <a href="matlab:edit test_lradi_filter.m">test_lradi_filter.m</a>
%       <a href="matlab:help test_lradi_nse_dae2">test_lradi_nse_dae2</a>, <a href="matlab:edit test_lradi_nse_dae2">test_lradi_nse_dae2.m</a>
%       <a href="matlab:help test_lradi_triple_chain_so1">test_lradi_triple_chain_so1</a>,  <a href="matlab:edit test_lradi_triple_chain_so1">test_lradi_triple_chain_so1.m</a>
%       <a href="matlab:help test_lradi_triple_chain_so2">test_lradi_triple_chain_so2</a>, <a href="matlab:edit test_lradi_triple_chain_so2">test_lradi_triple_chain_so2.m</a>
%       <a href="matlab:help test_lradi_ww_dae1">test_lradi_ww_dae1</a>, <a href="matlab:edit test_lradi_ww_dae1">test_lradi_ww_dae1.m</a>
%
%   See also MESS_LRNM.
%
%   References:
%   <a href="matlab:disp(mess_cite('Kue16'))">[1]</a>, <a href="matlab:disp(mess_cite('BenKS12'))">[2]</a>, <a href="matlab:disp(mess_cite('BenKS13a'))">[3]</a>,
%   <a href="matlab:disp(mess_cite('BenKS13'))">[4]</a>, <a href="matlab:disp(mess_cite('BenKS14b'))">[5]</a>, <a href="matlab:disp(mess_cite('Kue16'))">[6]</a>,
%   <a href="matlab:disp(mess_cite('Saa09'))">[7]</a>
%
%   Author: Maximilian Behr (MPI Magdeburg, CSC)

%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, see <http://www.gnu.org/licenses/>.
%
% Copyright (C) Peter Benner, Martin Koehler, Jens Saak and others
%               2009-2018
%

function [Z,status] = mess_lradi(eqn,opt)
    [Z,status] = mess_call('mess_lradi',eqn,opt);
end
