      DOUBLE PRECISION FUNCTION ZGEFNR(N,M,A,LDA)
      INTEGER N,M,LDA
      COMPLEX*16 A(LDA,*)
      INTEGER I,J
      DOUBLE PRECISION FNR

      FNR=0d0
      DO 100 J=1,M
       DO 110 I=1,N
        FNR = FNR+ABS(A(I,J))**2
110    CONTINUE
100   CONTINUE
      ZGEFNR = SQRT(FNR)

      END FUNCTION

